steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.cloudrun', '-t', 'us-central1-docker.pkg.dev/warehouse-489400/warehouse/inference-demo:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/warehouse-489400/warehouse/inference-demo:latest'
